server:
  port: 8001
spring:
  datasource:
#    url: jdbc:mysql://127.0.0.1:3306/himes-activiti?invoicing_management_system&useSSL=false&serverTimezone=Hongkong&characterEncoding=utf-8&autoReconnect=true&allowPublicKeyRetrieval=true
    url: jdbc:mysql://127.0.0.1:3306/activiti?invoicing_management_system&useSSL=false&serverTimezone=Hongkong&characterEncoding=utf-8&autoReconnect=true&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  activiti:
    check-process-definitions: false
    process-definition-location-prefix: classpath:/processes/
    database-schema-update: true

    createDiagramOnDeploy: false
    async-executor-activate: true

  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false



  logging:
    level: yuanh.himes.activi
